eureka:
  client:
    healthcheck:
      enabled: true   # 开启健康检查
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
#eureka-client-8802:
#  ribbon:
#    listOfServers: http://localhost:8802,http://localhost:8803
server:
  port: 8763
spring:
  application:
    name: sboot-feign-client
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true #开启请求压缩功能
      mimeTypes: text/xml;application/xml;application/json  #指定压缩请求数据类型
      minRequestSize: 2048   #如果传输超过该字节，就对其进行压缩
    reponse:
      enabled: true  #开启响应压缩功能
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
        isolation:
          thread:
            timeoutInMilliseconds: 300   #设置超时熔断时间